permissions:
    contents: read
    checks: write
    id-token: write

name: CI
on: [push]

jobs:
  lhci-and-dastardly:
    name: Lighthouse CI and Dastardly Scan
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Lighthouse CI
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.14.x

      # Step 3: Run Dastardly Scan
      - name: Run Dastardly Scan
        continue-on-error: true  # Allow subsequent steps to run even if this step fails
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://ginandjuice.shop'
          output-filename: dastardly-report.xml

      # Step 4: Run Lighthouse CI
      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      # Step 5 Upload XML as artifact
      - name: Upload scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
         name: dastardly-reports
         path: ${{ github.workspace }}/dastardly-report.xml
        
