name: CI
on: [push]

jobs:
  lhci-and-dastardly:
    name: Lighthouse CI and Dastardly Scan
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Lighthouse CI
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.14.x

      # Step 3: Run Dastardly Scan
      - name: Run Dastardly Scan
        continue-on-error: true  # Allow subsequent steps to run even if this step fails
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://yusufasik.com'  # Replace with your target URL

      # Step 4: Run Lighthouse CI
      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      # Step 5: Upload Dastardly Report as Artifact
      - name: Upload Dastardly Report
        uses: actions/upload-artifact@v3
        with:
          name: dastardly-report
          path: dastardly-report.html  # Path to the Dastardly report

      # Step 6: Upload Lighthouse CI Report as Artifact
      - name: Upload Lighthouse CI Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: .lighthouseci  # Path to the Lighthouse CI report directory
